//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.ServiceAuthNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAuthNS.IAuth")]
    public interface IAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Autorize", ReplyAction="http://tempuri.org/IAuth/AutorizeResponse")]
        string Autorize(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Autorize", ReplyAction="http://tempuri.org/IAuth/AutorizeResponse")]
        System.Threading.Tasks.Task<string> AutorizeAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Register", ReplyAction="http://tempuri.org/IAuth/RegisterResponse")]
        string Register(string user, string pass, string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Register", ReplyAction="http://tempuri.org/IAuth/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string user, string pass, string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/CreateMD5", ReplyAction="http://tempuri.org/IAuth/CreateMD5Response")]
        string CreateMD5(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/CreateMD5", ReplyAction="http://tempuri.org/IAuth/CreateMD5Response")]
        System.Threading.Tasks.Task<string> CreateMD5Async(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthChannel : ChatApp.ServiceAuthNS.IAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthClient : System.ServiceModel.ClientBase<ChatApp.ServiceAuthNS.IAuth>, ChatApp.ServiceAuthNS.IAuth {
        
        public AuthClient() {
        }
        
        public AuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Autorize(string user, string pass) {
            return base.Channel.Autorize(user, pass);
        }
        
        public System.Threading.Tasks.Task<string> AutorizeAsync(string user, string pass) {
            return base.Channel.AutorizeAsync(user, pass);
        }
        
        public string Register(string user, string pass, string firstName, string lastName) {
            return base.Channel.Register(user, pass, firstName, lastName);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string user, string pass, string firstName, string lastName) {
            return base.Channel.RegisterAsync(user, pass, firstName, lastName);
        }
        
        public string CreateMD5(string input) {
            return base.Channel.CreateMD5(input);
        }
        
        public System.Threading.Tasks.Task<string> CreateMD5Async(string input) {
            return base.Channel.CreateMD5Async(input);
        }
    }
}
