//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.ServiceChatNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceChatNS.IChat", CallbackContract=typeof(ChatApp.ServiceChatNS.IChatCallback))]
    public interface IChat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/SendMessageToAll", ReplyAction="http://tempuri.org/IChat/SendMessageToAllResponse")]
        void SendMessageToAll(string message, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/SendMessageToAll", ReplyAction="http://tempuri.org/IChat/SendMessageToAllResponse")]
        System.Threading.Tasks.Task SendMessageToAllAsync(string message, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/Connect", ReplyAction="http://tempuri.org/IChat/ConnectResponse")]
        void Connect(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/Connect", ReplyAction="http://tempuri.org/IChat/ConnectResponse")]
        System.Threading.Tasks.Task ConnectAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/Disconect", ReplyAction="http://tempuri.org/IChat/DisconectResponse")]
        void Disconect(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/Disconect", ReplyAction="http://tempuri.org/IChat/DisconectResponse")]
        System.Threading.Tasks.Task DisconectAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/NewMessage")]
        void NewMessage(string t);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/NewPrivateMessage")]
        void NewPrivateMessage(string t);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/RefreshListOnline")]
        void RefreshListOnline(System.Collections.Generic.List<string> list);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatChannel : ChatApp.ServiceChatNS.IChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatClient : System.ServiceModel.DuplexClientBase<ChatApp.ServiceChatNS.IChat>, ChatApp.ServiceChatNS.IChat {
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendMessageToAll(string message, string userName) {
            base.Channel.SendMessageToAll(message, userName);
        }
        
        public System.Threading.Tasks.Task SendMessageToAllAsync(string message, string userName) {
            return base.Channel.SendMessageToAllAsync(message, userName);
        }
        
        public void Connect(string token) {
            base.Channel.Connect(token);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string token) {
            return base.Channel.ConnectAsync(token);
        }
        
        public void Disconect(string token) {
            base.Channel.Disconect(token);
        }
        
        public System.Threading.Tasks.Task DisconectAsync(string token) {
            return base.Channel.DisconectAsync(token);
        }
    }
}
